### ISSUE TITLE
No dmg download

### ISSUE THREAD

**Issue by Jaredy899** [Alex313031/Mercury#153]
Doesn’t seem like there a macOS dmg download for the newest version in the releases

**Comment by onfaitr** [comment]
thank you for doing this request !
i'm going back here everyday to see if it's updated for mac users 😭

**Comment by onfaitr** [comment]
No news so far...

**Comment by Alex313031** [comment]
@Jaredy899 @onfaitr Sorry, the guy I use for building MacOS releases (by remoting into his mac) is currently very busy. I will get MacOS releases out as soon as I can. I just copied the title from the old release, so it says MacOS when in fact there are no .dmgs in the latest release.

**Comment by onfaitr** [comment]
Thanks for the reply, I will continue to come back here every day until i can use Mercury again as my default browser 😭
I'm on macOS 10.15 so i can't use the previous versions

**Comment by onfaitr** [comment]
What do you need exactly to build mercury on MacOS ? 
I'm willing to help 😅

**Comment by onfaitr** [comment]
I dropped out Mercury on mac... I now use Waterfox for a month now and i really enjoy it

**Comment by 6R1MR34P3R** [comment]
Any news on this? I relly would like to use Mercury on my Mac. I would like to help if needed

**Comment by peterjumper** [comment]
tried to build it but fail to do so:

```sh
appreciating
 0:00.61 W Clobber not needed.
 Config object not found by mach.
 0:00.87 Using Python 3.12.4 from /Users//.mozbuild/srcdirs/mozilla-unified-866bcde330fd/_virtualenvs/build/bin/python
 0:00.87 Adding configure options from /Users//mozilla-unified/mozconfig
 0:00.88   --enable-application=browser
 0:00.88   --disable-artifact-builds
 0:00.88   --enable-bootstrap
 0:00.88   --enable-release
 0:00.88   --disable-debug
 0:00.88   --disable-debug-symbols
 0:00.88   --disable-debug-js-modules
 0:00.88   --disable-tests
 0:00.88   --enable-clang-plugin
 0:00.88   --enable-lto
 0:00.88   --enable-optimize=-O3 -march=armv8.3-a+simd
 0:00.88   --enable-rust-simd
 0:00.88   --enable-hardening
 0:00.88   --enable-sandbox
 0:00.88   --enable-raw
 0:00.88   --enable-webrtc
 0:00.88   --enable-jxl
 0:00.88   --enable-av1
 0:00.88   --enable-eme=widevine
 0:00.88   --allow-addon-sideload
 0:00.88   --with-unsigned-addon-scopes=app,system
 0:00.88   --disable-parental-controls
 0:00.88   --disable-crashreporter
 0:00.88   --disable-updater
 0:00.88   --enable-geckodriver
 0:00.89   --without-wasm-sandboxed-libraries
 0:00.89   --with-google-location-service-api-keyfile=/Users//mozilla-unified/ga
 0:00.89   --with-google-safebrowsing-api-keyfile=/Users//mozilla-unified/ga
 0:00.89   --with-app-name=mercury
 0:00.89   --with-app-basename=Mercury
 0:00.89   --with-branding=browser/branding/mercury
 0:00.89   --with-l10n-base=/Users//mozilla-unified/browser/locales/en-US
 0:00.89   --with-distribution-id=com.alex313031.mercury
 0:00.89   OPT_LEVEL=3
 0:00.89   RUSTC_OPT_LEVEL=3
 0:00.89   MOZ_LTO=1
 0:00.89   RUSTC_OPT_LEVEL=3
 0:00.89   MOZ_SOURCE_CHANGESET=
 0:00.89   RUSTFLAGS=-C target-feature=+v8.3a -C codegen-units=1
 0:00.89   AUTOCLOBBER=1
 0:00.89   CXXFLAGS=-O3 -march=armv8.3-a+simd
 0:00.89   VERBOSE=1
 0:00.89   MOZ_CRASHREPORTER=0
 0:00.89   CPPFLAGS=-O3 -march=armv8.3-a+simd
 0:00.89   MOZ_REQUIRE_SIGNING=
 0:00.89   MOZ_DATA_REPORTING=0
 0:00.89   OPT_LEVEL=3
 0:00.89   MOZILLA_OFFICIAL=1
 0:00.89   MOZ_INCLUDE_SOURCE_INFO=1
 0:00.89   LDFLAGS=-Wl,-O3 -march=armv8.3-a+simd
 0:00.89   MOZ_OPTIMIZE=1
 0:00.89   MOZ_LTO=1
 0:00.89   MOZ_TELEMETRY_REPORTING=
 0:00.89   CFLAGS=-O3 -march=armv8.3-a+simd
 0:00.89 checking for vcs source checkout... hg
 0:00.91 checking for a shell... /bin/sh
 0:00.96 checking for host system type... aarch64-apple-darwin22.6.0
 0:00.96 checking for target system type... aarch64-apple-darwin22.6.0
 0:01.00 Traceback (most recent call last):
 0:01.00   File "/Users//mozilla-unified/configure.py", line 351, in <module>
 0:01.00     sys.exit(main(sys.argv))
 0:01.00              ^^^^^^^^^^^^^^
 0:01.00   File "/Users//mozilla-unified/configure.py", line 138, in main
 0:01.01     sandbox.include_file(os.path.join(os.path.dirname(__file__), "moz.configure"))
 0:01.01   File "/Users//mozilla-unified/python/mozbuild/mozbuild/configure/__init__.py", line 498, in include_file
 0:01.01     exec(code, self)
 0:01.01   File "/Users//mozilla-unified/moz.configure", line 232, in <module>
 0:01.01     include("build/moz.configure/libraries.configure", when="--enable-compile-environment")
 0:01.01   File "/Users//mozilla-unified/python/mozbuild/mozbuild/configure/__init__.py", line 872, in include_impl
 0:01.01     self.include_file(what)
 0:01.01   File "/Users//mozilla-unified/python/mozbuild/mozbuild/configure/__init__.py", line 498, in include_file
 0:01.01     exec(code, self)
 0:01.01   File "/Users//mozilla-unified/build/moz.configure/libraries.configure", line 30, in <module>
 0:01.01     have_raw_clock_monotonic_support = check_clock_monotonic_support()
 0:01.01                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 0:01.01   File "/Users//mozilla-unified/python/mozbuild/mozbuild/configure/__init__.py", line 916, in wrapper
 0:01.01     ret = template(*args, **kwargs)
 0:01.01           ^^^^^^^^^^^^^^^^^^^^^^^^^
 0:01.01   File "/Users//mozilla-unified/python/mozbuild/mozbuild/configure/__init__.py", line 1316, in wrapped
 0:01.01     return new_func(*args, **kwargs)
 0:01.01            ^^^^^^^^^^^^^^^^^^^^^^^^^
 0:01.01   File "/Users//mozilla-unified/build/moz.configure/libraries.configure", line 17, in check_clock_monotonic_support
 0:01.01     check_when = building_with_gnu_compatible_cc
 0:01.01                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 0:01.01 NameError: name 'building_with_gnu_compatible_cc' is not defined
*** Fix above errors and then restart with "./mach build"



```

appreciating all the developer here, latter will discover more about mercury.

**Comment by perdomon** [comment]
I'd love to see this browser available for Mac again soon. What can we do to help with that process?
