### ISSUE TITLE
Building Mercury from source

### ISSUE THREAD

**Issue by Joly0** [Alex313031/Mercury#178]
Hey guys, i am trying to build mercury for windows in an ubuntu docker container, that should be that big of an issue i guess, but i have some isses. First here is my dockerfile so anyone can understand what is happening:
```
FROM ubuntu:22.04

ENV SHELL /bin/bash

ENV PATH="/root/.cargo/bin:${PATH}"

RUN apt-get update && \
    apt-get install -y curl python3 clang llvm python3-pip git

RUN pip3 install Mercurial

RUN git clone https://github.com/Alex313031/Mercury.git $HOME/Mercury
RUN curl https://hg.mozilla.org/mozilla-central/raw-file/default/python/mozboot/bin/bootstrap.py -O && \
    python3 bootstrap.py --application-choice=browser --no-interactive && \
    mv /mozilla-unified $HOME/

WORKDIR /root/Mercury

RUN export TERM=xterm && \
    ./setup.sh --cross-avx2 && \
    ./build.sh
```

When i execute that, everything looks good so far, alot of microsoft stuff is installed, but at some point, i am facing this issue:
```
3:00.05 Unpacking Microsoft.VC.14.39.17.9.MFC.ARM64.Debug.base
 3:00.05 Unpacking Microsoft.VisualCpp.MFC.MBCS.arm64
 3:00.05 Unpacking Microsoft.VC.14.39.17.9.MFC.MBCS.arm64.base
 3:00.05 Unpacking Microsoft.VC.14.39.17.9.MFC.MBCS.arm64.Debug.base
 3:00.05 Unpacking Microsoft.VisualCpp.MFC.Redist.ARM64
 3:00.05 Unpacking Microsoft.VC.14.38.17.8.MFC.Redist.ARM64.base
 3:00.05 Unpacking Win11SDK_10.0.22621
 3:00.05 Extracting Application Verifier arm External Package (DesktopEditions)-arm_en-us.msi
 3:00.05 Traceback (most recent call last):
 3:00.05   File "/root/mozilla-unified/taskcluster/scripts/misc/get_vs.py", line 48, in <module>
 3:00.05     extractPackages(selected, dl_cache, unpacked)
 3:00.05   File "/root/mozilla-unified/third_party/python/vsdownload/vsdownload.py", line 534, in extractPackages
 3:00.05     unpackWin10SDK(dir, p["payloads"], dest)
 3:00.05   File "/root/mozilla-unified/third_party/python/vsdownload/vsdownload.py", line 519, in unpackWin10SDK
 3:00.05     subprocess.check_call(cmd, stdout=log)
 3:00.05   File "/usr/lib/python3.10/subprocess.py", line 364, in check_call
 3:00.05     retcode = call(*popenargs, **kwargs)
 3:00.05   File "/usr/lib/python3.10/subprocess.py", line 345, in call
 3:00.05     with Popen(*popenargs, **kwargs) as p:
 3:00.05   File "/usr/lib/python3.10/subprocess.py", line 971, in __init__
 3:00.05     self._execute_child(args, executable, preexec_fn, close_fds,
 3:00.05   File "/usr/lib/python3.10/subprocess.py", line 1863, in _execute_child
 3:00.05     raise child_exception_type(errno_num, err_msg, err_filename)
 3:00.06 FileNotFoundError: [Errno 2] No such file or directory: 'msiextract'
 3:00.06 ERROR: Command '['/root/.mozbuild/srcdirs/mozilla-unified-fb3fd3731f6b/_virtualenvs/build/bin/python', '/root/mozilla-unified/mach', '--log-no-times', 'python', '--virtualenv', 'build', '/root/mozilla-unified/taskcluster/scripts/misc/get_vs.py', 'build/vs/vs2022.yaml', 'vs']' returned non-zero exit status 1.
 3:00.06 ERROR: If you can't fix the above, retry with --disable-bootstrap.
*** Fix above errors and then restart with "./mach build"
```

I also tried changing the last few lines of the dockerfile to
```
RUN export TERM=xterm && \
    ./setup.sh --win-avx2 && \
    ./build.sh
```

But that didnt work aswell, i am getting this error:
```
0:00.47   RUSTFLAGS=-C target-cpu=haswell -C target-feature=+avx2 -C codegen-units=1
 0:00.47   MOZ_DATA_REPORTING=0
 0:00.47   VERBOSE=1
 0:00.47   WIN32_REDIST_DIR=/c/Program Files/Microsoft Visual Studio/2022/Community/VC/Redist/MSVC/14.38.33130/x64/Microsoft.VC143.CRT
 0:00.47   CFLAGS=-O3 -march=x86-64-v3 /clang:-O3 /clang:-ffp-contract=fast /arch:AVX2
 0:00.47   MOZ_REQUIRE_SIGNING=
 0:00.47   MOZ_INCLUDE_SOURCE_INFO=1
 0:00.47   CPPFLAGS=-O3 -march=x86-64-v3 /clang:-O3 /clang:-ffp-contract=fast /arch:AVX2
 0:00.47   POLLY=-mllvm -polly -mllvm -polly-2nd-level-tiling -mllvm -polly-loopfusion-greedy -mllvm -polly-pattern-matching-based-opts -mllvm -polly-position=before-vectorizer -mllvm -polly-vectorizer=stripmine
 0:00.47   CROSS_COMPILE=0
 0:00.47 checking for vcs source checkout... hg
 0:00.48 checking for a shell... /usr/bin/sh
 0:00.50 checking for host system type... x86_64-pc-linux-gnu
 0:00.50 checking for target system type... x86_64-pc-linux-gnu
 0:00.62 checking whether cross compiling... no
 0:00.66 Traceback (most recent call last):
 0:00.66   File "/root/mozilla-unified/configure.py", line 351, in <module>
 0:00.66     sys.exit(main(sys.argv))
 0:00.66   File "/root/mozilla-unified/configure.py", line 141, in main
 0:00.66     sandbox.run()
 0:00.66   File "/root/mozilla-unified/python/mozbuild/mozbuild/configure/__init__.py", line 522, in run
 0:00.66     self._value_for(option)
 0:00.66   File "/root/mozilla-unified/python/mozbuild/mozbuild/configure/__init__.py", line 627, in _value_for
 0:00.66     return self._value_for_option(obj)
 0:00.66   File "/root/mozilla-unified/python/mozbuild/mozbuild/util.py", line 1041, in method_call
 0:00.66     cache[args] = self.func(instance, *args)
 0:00.66   File "/root/mozilla-unified/python/mozbuild/mozbuild/configure/__init__.py", line 694, in _value_for_option
 0:00.66     raise InvalidOptionError(
 0:00.67 mozbuild.configure.options.InvalidOptionError: WIN32_REDIST_DIR is not available in this configuration
*** Fix above errors and then restart with "./mach build"
 0:00.70 W Exception when writing resource usage file: [Errno 2] No such file or directory: '/root/mozilla-unified/obj-x86_64-pc-linux-gnu/instrumented/.mozbuild/profile_build_resources.json'
```

**Comment by SashaXser** [comment]
Do you have a solution to the problem?

**Comment by Joly0** [comment]
> Do you have a solution to the problem?

Sadly no, i gave up after trying for a while. If you find a solution, feel free to ping me

**Comment by SashaXser** [comment]
> > Do you have a solution to the problem?
> 
> Sadly no, i gave up after trying for a while. If you find a solution, feel free to ping me

The first error is very easy to solve, just install msitools (apt install msitools)

The second error is related to the ga file, the ga file from the mozconfig folder in the Mercury folder is not copied to /root/mozilla-unified/

Copy it manually like this: cp ga /root/mozilla-unified/ga

**Comment by SashaXser** [comment]
@Joly0 I compiled Firefox 127 AVX2, compiled for about an hour, [enjoy it](https://kappa.lol/nEcrS)

**Comment by Joly0** [comment]
> @Joly0 I compiled Firefox 127 AVX2, compiled for about an hour, [enjoy it](https://kappa.lol/nEcrS)

Do you mind sending exact instructions what you did, what software and os you use, etc? Would be really grateful :)

**Comment by SashaXser** [comment]
@Joly0 I think I did everything as instructed, fixed those two errors, and everything went fine. I just had to run ./setup.sh again (there was an error with brands).

I also did rustup target add x86_64-pc-windows-msvc and I don't think I had any other problems. Write here, I may be of some help to you.

**Comment by gz83** [comment]
Please choose versions compiled by third parties with caution. We do not provide support for problems in versions compiled by third parties.
