### ISSUE TITLE
Cant compile.

### ISSUE THREAD

**Issue by iicuken** [Alex313031/Mercury#200]
Good day.I am trying to compile Mercury from source. I have Arch linux latest with all build tools installed.
Ive done bootstrap:
  On question "Please choose the version of Firefox you want to build "  i select "Firefox for Desktop Artifact Mode [default]" same  as "Firefox for Desktop".
 Bootstrap successive.

Ive done setup.
Setup successive.

Ive don build.
Build fail with error: 

0:00.48 checking for vcs source checkout... hg
 0:00.49 checking for a shell... /usr/bin/sh
 0:00.52 checking for host system type... x86_64-pc-linux-gnu
 0:00.53 checking for target system type... x86_64-pc-linux-gnu
 0:00.57 Traceback (most recent call last):
 0:00.57   File "/home/qq/tmpfs1/mozsrsrc/configure.py", line 351, in <module>
 0:00.57     sys.exit(main(sys.argv))
 0:00.57              ^^^^^^^^^^^^^^
 0:00.57   File "/home/qq/tmpfs1/mozsrsrc/configure.py", line 138, in main
 0:00.57     sandbox.include_file(os.path.join(os.path.dirname(__file__), "moz.configure"))
 0:00.57   File "/home/qq/tmpfs1/mozsrsrc/python/mozbuild/mozbuild/configure/__init__.py", line 498, in include_file
 0:00.57     exec(code, self)
 0:00.57   File "/home/qq/tmpfs1/mozsrsrc/moz.configure", line 232, in <module>
 0:00.57     include("build/moz.configure/libraries.configure", when="--enable-compile-environment")
 0:00.57   File "/home/qq/tmpfs1/mozsrsrc/python/mozbuild/mozbuild/configure/__init__.py", line 872, in include_impl
 0:00.57     self.include_file(what)
 0:00.57   File "/home/qq/tmpfs1/mozsrsrc/python/mozbuild/mozbuild/configure/__init__.py", line 498, in include_file
 0:00.58     exec(code, self)
 0:00.58   File "/home/qq/tmpfs1/mozsrsrc/build/moz.configure/libraries.configure", line 30, in <module>
 0:00.58     have_raw_clock_monotonic_support = check_clock_monotonic_support()
 0:00.58                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 0:00.58   File "/home/qq/tmpfs1/mozsrsrc/python/mozbuild/mozbuild/configure/__init__.py", line 916, in wrapper
 0:00.58     ret = template(*args, **kwargs)
 0:00.58           ^^^^^^^^^^^^^^^^^^^^^^^^^
 0:00.58   File "/home/qq/tmpfs1/mozsrsrc/python/mozbuild/mozbuild/configure/__init__.py", line 1316, in wrapped
 0:00.58     return new_func(*args, **kwargs)
 0:00.58            ^^^^^^^^^^^^^^^^^^^^^^^^^
 0:00.58   File "/home/qq/tmpfs1/mozsrsrc/build/moz.configure/libraries.configure", line 17, in check_clock_monotonic_support
 0:00.58     check_when = building_with_gnu_compatible_cc
 0:00.58                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 0:00.58 NameError: name 'building_with_gnu_compatible_cc' is not defined
*** Fix above errors and then restart with "./mach build"
 0:00.59 W Exception when writing resource usage file: [Errno 2] No such file or directory: '/home/qq/tmpfs1/mozsrsrc/obj-x86_64-pc-linux-gnu/instrumented/.mozbuild/profile_build_resources.json'

 NameError: name 'building_with_gnu_compatible_cc' is not defined

Pls help.

**Comment by gz83** [comment]
https://github.com/Alex313031/Mercury/tree/main/docs

**Comment by zenmetsu** [comment]
I receive the same build error, however I did follow the build documents and selected everything correctly (including the non-Artifact build).

I'm not sure why the link to the docs was posted without further comment.  I have been over the docs several times and nothing called out therein differs from actions taken on my end.

**Comment by SashaXser** [comment]
> I receive the same build error, however I did follow the build documents and selected everything correctly (including the non-Artifact build).
> 
> I'm not sure why the link to the docs was posted without further comment. I have been over the docs several times and nothing called out therein differs from actions taken on my end.

Mercury has been out for almost 4 months now, some files are out of date there. I think you can fix it if you exclude some files from the installation. That is, in setup.sh change it: 

```
cp -r -v ./app/. ${HG_SRC_DIR}/browser/app/ &&
cp -r -v ./browser/. ${HG_SRC_DIR}/browser/ &&
cp -r -v ./build/. ${HG_SRC_DIR}/build/ &&
cp -r -v ./devtools/. ${HG_SRC_DIR}/devtools/ &&
cp -r -v ./ipc/. ${HG_SRC_DIR}/ipc/ &&
cp -r -v ./moz.build ${HG_SRC_DIR}/ &&
cp -r -v ./netwerk/. ${HG_SRC_DIR}/netwerk/ &&
cp -r -v ./other-licenses/. ${HG_SRC_DIR}/other-licenses/ &&
mkdir -p -v ${HG_SRC_DIR}/policies &&
cp -r -v ./policies/. ${HG_SRC_DIR}/policies/ &&
cp -r -v ./toolkit/. ${HG_SRC_DIR}/toolkit/ &&
cp -r -v ./testing/. ${HG_SRC_DIR}/testing/ &&
cp -v ./mozconfigs/ga ${HG_SRC_DIR} &&
cp -v ./mozconfigs/mozconfig ${HG_SRC_DIR} &&
```

to this:

```
cp -r -v ./app/profile. ${HG_SRC_DIR}/browser/app/profile &&
cp -r -v ./browser/branding. ${HG_SRC_DIR}/browser/branding &&
# cp -r -v ./build/. ${HG_SRC_DIR}/build/ &&
# cp -r -v ./devtools/. ${HG_SRC_DIR}/devtools/ &&
# cp -r -v ./ipc/. ${HG_SRC_DIR}/ipc/ &&
# cp -r -v ./moz.build ${HG_SRC_DIR}/ &&
# cp -r -v ./netwerk/. ${HG_SRC_DIR}/netwerk/ &&
cp -r -v ./other-licenses/. ${HG_SRC_DIR}/other-licenses/ &&
mkdir -p -v /root/mozilla-unified/policies &&
cp -r -v ./policies/. /root/mozilla-unified/policies/ &&
# cp -r -v ./toolkit/. ${HG_SRC_DIR}/toolkit/ &&
# cp -r -v ./testing/. ${HG_SRC_DIR}/testing/ &&
cp -v ./mozconfigs/ga ${HG_SRC_DIR} &&
cp -v ./mozconfigs/mozconfig ${HG_SRC_DIR} &&
```

**Comment by sheikh1233** [comment]
I have been having the same issue on Gentoo, havent tried not doing setup

**Comment by sheikh1233** [comment]
Not doing setup seems like it would be counterintuitive, because it copies the source files for mercury, making it so that if you don't run it you just get normal Firefox
